# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/_r-mutex-1.0.1-anacondar_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2020.4.5.1-hecc5488_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ld_impl_linux-64-2.34-h53a641e_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libgfortran-ng-7.3.0-hdf63c60_5.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libstdcxx-ng-9.2.0-hdf63c60_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/llvm-openmp-10.0.0-hc9558a2_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/mpi-1.0-mpich.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/_openmp_mutex-4.5-1_llvm.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/binutils_impl_linux-64-2.34-h53a641e_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libgomp-9.2.0-h24d8f2e_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/binutils_linux-64-2.34-hc952b39_18.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libgcc-ng-9.2.0-h24d8f2e_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/bzip2-1.0.8-h516909a_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/expat-2.2.9-he1b5a44_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gcc_impl_linux-64-7.3.0-hd420e75_5.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ghostscript-9.22-hf484d3e_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/giflib-5.1.7-h516909a_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/graphite2-1.3.13-he1b5a44_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/icu-58.2-hf484d3e_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jbig-2.1-h516909a_2002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jpeg-9c-h14c3975_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libffi-3.2.1-he1b5a44_1007.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libiconv-1.15-h516909a_1006.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libopenblas-0.3.9-h5ec1e0e_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libtool-2.4.6-h14c3975_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libuuid-2.32.1-h14c3975_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/lz4-c-1.9.2-he1b5a44_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/make-4.3-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/mpich-3.3.2-hc856adb_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ncurses-6.1-hf484d3e_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/openssl-1.1.1g-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pcre-8.44-he1b5a44_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/perl-5.26.2-h516909a_1006.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pixman-0.38.0-h516909a_1003.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pkg-config-0.29.2-h516909a_1006.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pthread-stubs-0.4-h14c3975_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/sed-4.7-h1bed415_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-kbproto-1.0.7-h14c3975_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libice-1.0.10-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxau-1.0.9-h14c3975_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxdmcp-1.1.3-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-renderproto-0.11.1-h14c3975_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-xextproto-7.3.0-h14c3975_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-xproto-7.0.31-h14c3975_1007.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xz-5.2.5-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/yaml-0.2.4-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/zlib-1.2.11-h516909a_1006.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/fftw-3.3.8-mpi_mpich_h3f9e1be_1010.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gcc_linux-64-7.3.0-h553295d_18.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gettext-0.19.8.1-hc5be6a0_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gfortran_impl_linux-64-7.3.0-hdf63c60_5.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gxx_impl_linux-64-7.3.0-hdf63c60_5.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libblas-3.8.0-16_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libedit-3.1.20170329-hf8c457e_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libpng-1.6.37-hed695b0_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libprotobuf-3.11.4-h8b12597_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libssh2-1.8.2-h22169c7_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libxcb-1.13-h14c3975_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libxml2-2.9.9-h13577e0_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/readline-8.0-hf8c457e_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tk-8.6.10-hed695b0_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libsm-1.2.3-h84519dc_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/zstd-1.4.4-h6597ccf_3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/bwidget-1.9.14-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/freetype-2.10.1-he06d7ca_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gfortran_linux-64-7.3.0-h553295d_18.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gxx_linux-64-7.3.0-h553295d_18.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/krb5-1.16.4-h2fd8d38_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libcblas-3.8.0-16_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/liblapack-3.8.0-16_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libtiff-4.1.0-hc3755c2_3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/sqlite-3.30.1-hcee41ef_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tktable-2.10-h555a92e_3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libx11-1.6.9-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/fontconfig-2.13.1-he4413a7_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gsl-2.5-h294904e_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libcurl-7.68.0-hda55be3_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libwebp-1.0.2-hf4e8a37_4.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/openjpeg-2.3.1-h981e76c_3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python-3.8.2-he5300dc_7_cpython.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxext-1.3.4-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxrender-0.9.10-h516909a_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxt-1.1.5-h516909a_1003.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/appdirs-1.4.3-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/async-timeout-3.0.1-py_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/attrs-19.3.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cachetools-3.1.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/configargparse-1.2.3-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/crc32c-2.0-py38h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/curl-7.68.0-hf8cf82a_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/decorator-4.4.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/docutils-0.15.2-py38_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/filechunkio-1.8-py_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/ftputil-3.4-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/glib-2.64.2-h6f030ca_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/idna-2.9-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/ipython_genutils-0.2.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jmespath-0.9.5-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/multidict-4.7.5-py38h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/prettytable-0.7.2-py_3.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyasn1-0.4.8-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pycparser-2.20-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python_abi-3.8-1_cp38.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pytz-2020.1-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ratelimiter-1.2.0-py38_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/six-1.14.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/smmap-3.0.2-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/toposort-1.5-py_3.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/xmlrunner-1.7.7-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxpm-3.5.13-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/zipp-3.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cairo-1.16.0-h18b612c_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/certifi-2020.4.5.1-py38h32f6830_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cffi-1.14.0-py38hd463f26_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/chardet-3.0.4-py38h32f6830_1006.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/datrie-0.8.2-py38h1e0a361_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/gitdb-4.0.4-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/google-resumable-media-0.5.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/importlib-metadata-1.6.0-py38h32f6830_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libcroco-0.6.13-h8d621e5_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/markupsafe-1.1.1-py38h1e0a361_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/numpy-1.18.1-py38h8854b6b_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/psutil-5.7.0-py38h1e0a361_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyasn1-modules-0.2.7-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyrsistent-0.16.0-py38h1e0a361_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pysocks-1.7.1-py38h32f6830_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/python-dateutil-2.8.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/python-irodsclient-0.8.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyyaml-5.3.1-py38h1e0a361_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/rsa-4.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/traitlets-4.3.3-py38h32f6830_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/wrapt-1.12.1-py38h1e0a361_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/yarl-1.3.0-py38h516909a_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/aiohttp-3.6.2-py38h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/brotlipy-0.7.0-py38h1e0a361_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cryptography-2.9.2-py38h766eaa4_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/gitpython-3.1.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gobject-introspection-1.58.2-py38h03d966d_1004.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/harfbuzz-2.4.0-h37c48d4_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/importlib_metadata-1.6.0-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jupyter_core-4.6.3-py38h32f6830_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pandas-1.0.3-py38hcb8c335_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pynacl-1.3.0-py38h516909a_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/setuptools-46.1.3-py38h32f6830_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/aioeasywebdav-2.4.0-py38_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gdk-pixbuf-2.36.12-h3f25603_1005.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/google-auth-1.14.1-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jinja2-2.11.2-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jsonschema-3.2.0-py38h32f6830_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/networkx-2.4-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pango-1.40.14-he7ab937_1005.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/protobuf-3.11.4-py38h950e882_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pygments-2.6.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyopenssl-19.1.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/wheel-0.34.2-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/googleapis-common-protos-1.51.0-py38h32f6830_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/graphviz-2.38.0-hf68f40c_1011.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/librsvg-2.44.14-h11c8777_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/nbformat-5.0.6-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pip-20.0.2-py_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-base-3.6.1-h8900bf8_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/urllib3-1.25.9-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/bcrypt-3.1.7-py38h1e0a361_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/botocore-1.15.48-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/imagemagick-7.0.8_54-pl526h39023e4_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pygraphviz-1.5-py38h1e0a361_1002.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/r-boot-1.3_25-r36h6115d3f_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-cluster-2.1.0-r36h9bbef5b_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/r-codetools-0.2_16-r36h6115d3f_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-foreign-0.8_76-r36hcdcec82_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-kernsmooth-2.23_17-r36hfa343cc_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-lattice-0.20_41-r36hcdcec82_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-mass-7.3_51.6-r36hcdcec82_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-rpart-4.1_15-r36hcdcec82_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-spatial-7.3_12-r36hcdcec82_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/requests-2.23.0-pyh8c360ce_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/dropbox-9.4.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/google-api-core-1.17.0-py38h32f6830_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/paramiko-2.7.1-py38_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-class-7.3_17-r36hcdcec82_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-matrix-1.2_18-r36h7fa42b6_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-nlme-3.1_147-r36h9bbef5b_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-nnet-7.3_14-r36hcdcec82_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/s3transfer-0.3.3-py38h32f6830_1.tar.bz2
https://conda.anaconda.org/bioconda/noarch/snakemake-minimal-5.15.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/boto3-1.12.48-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/google-cloud-core-1.3.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pysftp-0.2.9-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-mgcv-1.8_31-r36h7fa42b6_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-survival-3.1_12-r36hcdcec82_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/google-cloud-storage-1.28.0-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/r-recommended-3.6-r36_1003.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/r-3.6-r36_1003.tar.bz2
https://conda.anaconda.org/bioconda/noarch/snakemake-5.15.0-0.tar.bz2
